ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS appearance_mode VARCHAR(10) DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS brand_preset VARCHAR(20) DEFAULT 'dlight',
  ADD COLUMN IF NOT EXISTS primary_color VARCHAR(7) DEFAULT '#B08D57',
  ADD COLUMN IF NOT EXISTS accent_color VARCHAR(7) DEFAULT '#D4AF67',
  ADD COLUMN IF NOT EXISTS sidebar_style VARCHAR(10) DEFAULT 'dark',
  ADD COLUMN IF NOT EXISTS interface_density VARCHAR(12) DEFAULT 'comfortable';

